# Generated by Django 4.0.3 on 2022-04-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id_Candidate', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=30, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Описание кандидата')),
                ('image', models.CharField(max_length=5, verbose_name='Фото кандидата')),
            ],
        ),
        migrations.CreateModel(
            name='territory',
            fields=[
                ('id_Terr', models.AutoField(primary_key=True, serialize=False)),
                ('territory_Name', models.CharField(max_length=30, verbose_name='Территория проведения выборов')),
            ],
        ),
        migrations.CreateModel(
            name='vote_Grade',
            fields=[
                ('id_Grade', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('name', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id_Vote', models.AutoField(primary_key=True, serialize=False)),
                ('id_Candidate', models.ManyToManyField(to='cik.candidate', verbose_name='Кандидат')),
                ('id_Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cik.vote_grade', verbose_name='Уровень выборов')),
                ('id_Terr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cik.territory', verbose_name='Территория выборов')),
            ],
        ),
        migrations.AddField(
            model_name='territory',
            name='id_Grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cik.vote_grade', verbose_name='Уровень выборов'),
        ),
    ]
