# Generated by Django 4.0.3 on 2022-04-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='id_Candidate',
        ),
        migrations.CreateModel(
            name='voteCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cik.candidate', verbose_name='Кандидат')),
                ('id_Vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cik.vote', verbose_name='Выборы')),
            ],
        ),
    ]
