# Generated by Django 4.0.3 on 2022-04-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cik', '0002_remove_vote_id_candidate_votecandidate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='candidate',
            new_name='candidateModel',
        ),
        migrations.RenameModel(
            old_name='territory',
            new_name='territoryModel',
        ),
        migrations.RenameModel(
            old_name='voteCandidate',
            new_name='voteCandidateModel',
        ),
        migrations.RenameModel(
            old_name='vote_Grade',
            new_name='voteGradeModel',
        ),
        migrations.RenameModel(
            old_name='vote',
            new_name='voteModel',
        ),
    ]
