# Generated by Django 4.0.3 on 2022-05-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cik', '0003_rename_candidate_candidatemodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatemodel',
            options={'verbose_name': 'Кандидаты', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AlterModelOptions(
            name='territorymodel',
            options={'verbose_name': 'Территория', 'verbose_name_plural': 'Территория'},
        ),
        migrations.AlterModelOptions(
            name='votegrademodel',
            options={'verbose_name': 'Уровень выборов', 'verbose_name_plural': 'Уровень выборов'},
        ),
        migrations.AlterModelOptions(
            name='votemodel',
            options={'verbose_name': 'Выборы', 'verbose_name_plural': 'Выборы'},
        ),
        migrations.AlterField(
            model_name='candidatemodel',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фото кандидата'),
        ),
    ]
